# Generated by Django 3.2 on 2021-05-03 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210503_1052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.RemoveField(
            model_name='post',
            name='header_image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
